CREATE USER GEEKERS IDENTIFIED BY oracle;
GRANT CONNECT TO GEEKERS;
GRANT CONNECT, RESOURCE, DBA TO GEEKERS;
GRANT CREATE SESSION TO GEEKERS;
GRANT DBA TO GEEKERS;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to GEEKERS;
GRANT UNLIMITED TABLESPACE TO GEEKERS;
GRANT CREATE MATERIALIZED VIEW TO GEEKERS;
GRANT CREATE TABLE TO GEEKERS;
GRANT GLOBAL QUERY REWRITE TO GEEKERS;
GRANT SELECT ANY TABLE TO GEEKERS;

CREATE TABLE USUARIO (
  id_usuario NUMBER,
  nome VARCHAR2(225) NOT NULL ,
  login VARCHAR2 (255) NOT NULL,
  email VARCHAR2(225) NOT NULL ,
  telefone VARCHAR2(225) NOT NULL ,
  senha VARCHAR2(225) NOT NULL ,
  dataNascimento date NOT NULL ,
  sexo CHAR(1) NOT NULL ,
  ativo CHAR(1) NOT NULL,
  PRIMARY KEY (id_usuario)
);

CREATE TABLE HOBBIE (
  id_hobbie NUMBER NOT NULL,
  tipo_hobbie char(1) NOT NULL,
  descricao VARCHAR2(225) NOT NULL,
  id_usuario NUMBER,
  PRIMARY KEY (id_hobbie),
   CONSTRAINT FK_HOBBIE_USUARIO_ID_USUARIO
   FOREIGN KEY (id_usuario)
   REFERENCES USUARIO(id_usuario)
);

CREATE TABLE COMENTARIO (
  id_comentario NUMBER,
  comentario VARCHAR2(225) NOT NULL,
  id_usuario NUMBER NOT NULL,
  PRIMARY KEY (id_comentario),
  CONSTRAINT FK_COMENT_USUARIO_ID_USUARIO
   FOREIGN KEY (id_usuario)
   REFERENCES USUARIO(id_usuario)
);

CREATE TABLE DESAFIO (
  id_desafio NUMBER,
  pergunta VARCHAR2(225),
  resposta VARCHAR2(225),
  id_usuario NUMBER,
  PRIMARY KEY (id_desafio),
  CONSTRAINT FK_DESAFIO_USUARIO_ID_USUARIO
   FOREIGN KEY (id_usuario)
   REFERENCES USUARIO(id_usuario)
);

CREATE TABLE MATCH (
  id_match NUMBER,
  id_usuario NUMBER,
  PRIMARY KEY (id_match),
  CONSTRAINT FK_MATCH_USUARIO_ID_USUARIO
   FOREIGN KEY (id_usuario)
   REFERENCES USUARIO(id_usuario)
);

CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_HOBBIE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_DESAFIO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_MATCH
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_COMENTARIO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;



CREATE TABLE CARGO (
    ID_CARGO NUMBER NOT NULL,
    NOME varchar2(512) UNIQUE NOT NULL,
    PRIMARY KEY(ID_CARGO)
);

CREATE SEQUENCE seq_cargo
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
  
INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_ADMIN'); -- 1

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_USUARIO'); -- 2

CREATE TABLE USUARIO_CARGO (
    ID_USUARIO NUMBER NOT NULL,
    ID_CARGO NUMBER NOT NULL,
    PRIMARY KEY(ID_USUARIO, ID_CARGO),
    CONSTRAINT FK_USUARIO_CARGO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO),
  	CONSTRAINT FK_USUARIO_CARGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);